name: Tests

on: [push]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
        python-version: ['3.6.7']

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run:
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Install package
      run:
        pip install -e .
    - name: Test nonlinear lmpc controller with pytest
      run:
        pytest tests/nlmpc_test.py --doctest-modules
    - name: Test i2lqr controller with pytest
      run:
        pytest tests/ilqr_test.py --doctest-modules